@BASE_URL = http://localhost:8000/api/v1

###

# Регистрация пользователей

POST {{BASE_URL}}/user
Content-Type: application/json

{
  "name": "admin",
  "password": "pwd",
  "role": "admin"
}

###

POST {{BASE_URL}}/user/
Content-Type: application/json

{
  "name": "doshamine",
  "password": "pwd"
}

###

POST {{BASE_URL}}/user/
Content-Type: application/json

{
  "name": "dashwer",
  "password": "pwd"
}

###

# Вход под разными пользователями

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "name": "admin",
  "password": "pwd"
}

###

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "name": "doshamine",
  "password": "pwd"
}

###

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "name": "dashwer",
  "password": "pwd"
}

###

# Действия, доступные только для авторизованных пользователей

PATCH {{BASE_URL}}/user/2
Content-Type: application/json
x-token: 5b98e035-cdb1-48dc-82ee-3bc3a020f9a2

{
  "password": "123"
}

###

DELETE {{BASE_URL}}/user/3
Content-Type: application/json
x-token: ec7c42ed-d0f1-449e-9d56-581d384e55d3

###

POST {{BASE_URL}}/advertisement/
Content-Type: application/json
x-token: 5b98e035-cdb1-48dc-82ee-3bc3a020f9a2

{
  "title": "Срочно",
  "description": "Продаю",
  "price": 10.9,
  "author": "Кеша"
}

###

PATCH {{BASE_URL}}/advertisement/1
Content-Type: application/json
x-token: 8d657015-4487-48f2-b031-2b3f3c44555d

{
  "price": 1.9,
  "author": "Саня"
}

###

DELETE {{BASE_URL}}/advertisement/2
Content-Type: application/json
x-token: 8d657015-4487-48f2-b031-2b3f3c44555d

###

POST {{BASE_URL}}/advertisement/
Content-Type: application/json
x-token: 8d657015-4487-48f2-b031-2b3f3c44555d

{
  "title": "Несрочно",
  "description": "Тоже продаю",
  "price": 100.9,
  "author": "Иннокентий"
}

###

# Действия, доступные для неавторизованных пользователей

GET {{BASE_URL}}/user/1
Content-Type: application/json

###

GET {{BASE_URL}}/advertisement/1
Content-Type: application/json

###

GET {{BASE_URL}}/advertisement/
Content-Type: application/json

{
  "title": "Срочно",
  "author": "Саня"
}

###

